# id: 1
server:
  address: "server:12345"
loop:
  amount: 1
  period: "5s"
log:
  level: "INFO"
batch:
  maxAmount: 10
# bet:
#   name: "Santiago Lionel"
#   last_name: "Lorca"
#   document: "30904465"
#   birth_date: "1999-03-17"
#   number: "7574"