name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_APUESTA_NOMBRE=Santiago
      - CLI_APUESTA_APELLIDO=Lorca
      - CLI_APUESTA_DOCUMENTO=30904465
      - CLI_APUESTA_NACIMIENTO=1999-03-17
      - CLI_APUESTA_NUMERO=7574
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
